##############################################################################
#  Copyright Christopher Kormanyos 2023 - 2024.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Osek_pi_crunch_cm3
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-gcc-arm-none-eabi:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: update-tools
        run: |
          sudo sudo apt-get update -y
          sudo apt-get install -y gcc-arm-none-eabi
      - name: target-gcc-arm-none-eabi
        run: |
          bash Build.sh
          ls -la ./Output/Osek_pi_crunch_cm3.elf ./Output/Osek_pi_crunch_cm3.hex
